### ISSUE TITLE
Swift 5.0.1 cannot be imported by the Swift 5.1

### ISSUE THREAD

**Issue by zeucxb** [sad1996/flutter_zendesk#1]
`error: module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1`

**Comment by sadaks-me** [comment]
Since there is no zendesk release build available for swift 5.1 right now, we’ve to use the branch for time being.

Add this line to your app’s ios/Podfile,

pod 'ZendeskSDK', :git => 'https://github.com/zendesk/zendesk_sdk_ios.git', :branch => '3.0.1-swift5.1-GM'

Once they release a stable build for Swift 5.1 we can remove this line.
